# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EasyQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='some answ', max_length=200)),
                ('first_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('second_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('third_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('fourth_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('good_answ', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HardQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='some answ', max_length=200)),
                ('first_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('second_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('third_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('fourth_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('good_answ', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MediumQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='some answ', max_length=200)),
                ('first_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('second_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('third_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('fourth_answ', models.CharField(blank=True, default='some answ', max_length=50)),
                ('good_answ', models.IntegerField(default=0)),
            ],
        ),
    ]
