# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennis',
            name='test_field',
        ),
        migrations.AddField(
            model_name='tennis',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tennis',
            name='first_answ',
            field=models.CharField(default='some answ', max_length=50),
        ),
        migrations.AddField(
            model_name='tennis',
            name='fourth_answ',
            field=models.CharField(default='some answ', max_length=50),
        ),
        migrations.AddField(
            model_name='tennis',
            name='good_answ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tennis',
            name='question',
            field=models.CharField(default='some answ', max_length=200),
        ),
        migrations.AddField(
            model_name='tennis',
            name='second_answ',
            field=models.CharField(default='some answ', max_length=50),
        ),
        migrations.AddField(
            model_name='tennis',
            name='third_answ',
            field=models.CharField(default='some answ', max_length=50),
        ),
    ]
