# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_auto_20170812_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennis',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=0),
        ),
    ]
