# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0005_auto_20170817_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyquest',
            name='first_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='easyquest',
            name='fourth_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='easyquest',
            name='second_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='easyquest',
            name='third_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
    ]
