# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0006_auto_20170823_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyquest',
            name='good_answ',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='easyquest',
            name='question',
            field=models.CharField(blank=True, default='some answ', max_length=200),
        ),
    ]
