# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0007_auto_20170823_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardquest',
            name='first_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='hardquest',
            name='fourth_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='hardquest',
            name='question',
            field=models.CharField(blank=True, default='some answ', max_length=200),
        ),
        migrations.AlterField(
            model_name='hardquest',
            name='second_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='hardquest',
            name='third_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediumquest',
            name='first_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediumquest',
            name='fourth_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediumquest',
            name='question',
            field=models.CharField(blank=True, default='some answ', max_length=200),
        ),
        migrations.AlterField(
            model_name='mediumquest',
            name='second_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediumquest',
            name='third_answ',
            field=models.CharField(blank=True, default='some answ', max_length=50),
        ),
    ]
